# Generated by Django 6.0.2 on 2026-03-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0004_usuario_foto_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='anuncios/')),
                ('tipo', models.CharField(choices=[('imagen', 'Solo imagen'), ('imagen_texto', 'Imagen con texto'), ('imagen_boton', 'Imagen con boton')], default='imagen', max_length=20)),
                ('texto_boton', models.CharField(blank=True, max_length=50)),
                ('url_boton', models.CharField(blank=True, max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='TuTallerApp.establecimiento')),
            ],
            options={
                'ordering': ['orden', '-creado_en'],
            },
        ),
    ]
