# Generated by Django 6.0.3 on 2026-03-29 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0006_cita_agenda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TuTallerApp.establecimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='TuTallerApp.servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
