# Generated by Django 6.0.3 on 2026-04-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0007_cita_establecimiento_cita_servicio_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TuTallerApp.establecimiento'),
            preserve_default=False,
        ),
    ]
